import { Category, Question } from '../types/game';

export const defaultCategories: Category[] = [
  {
    id: 'friends',
    name: 'Bạn Bè',
    description: 'Những câu hỏi dành cho bạn bè thân thiết',
    color: '#2ecc71',
  },
  {
    id: '18+',
    name: '18+',
    description: 'Những câu hỏi dành cho người trên 18 tuổi',
    color: '#9b59b6',
  },
];

// Default players
export const defaultPlayers: string[] = [
  'Mợ Linh',
  'Cậu Công',
  'Mợ Yao',
  'A2 Tiến',
  'Mợ Hân',
  'Cậu Nô',
  'Cậu Qin',
  'Quang Tèo',
  'Mợ Mi',
];

export const defaultQuestions: Question[] = [
  {
    id: '1',
    type: 'truth',
    text: 'Điều gì là kỷ niệm "đầu tiên" đáng nhớ nhất của bạn?',
    category: '18+',
  },
  {
    id: '2',
    type: 'truth',
    text: 'Bạn đã bao giờ nói dối để có được "cơ hội" với ai đó chưa?',
    category: '18+',
  },
  {
    id: '3',
    type: 'truth',
    text: 'Bạn đã bao giờ bị bắt gặp trong tình huống "nhạy cảm" chưa?',
    category: '18+',
  },
  {
    id: '4',
    type: 'truth',
    text: 'Điều gì khiến bạn bị kích thích nhất?',
    category: '18+',
  },
  {
    id: '5',
    type: 'truth',
    text: 'Bạn đã bao giờ có cảm xúc với người yêu của bạn bè chưa?',
    category: '18+',
  },
  {
    id: '6',
    type: 'truth',
    text: 'Bạn thích bị trói buộc hay là người trói buộc?',
    category: '18+',
  },
  {
    id: '7',
    type: 'truth',
    text: 'Bạn đã bao giờ gửi tin nhắn "nóng bỏng" cho người không phải là người yêu chưa?',
    category: '18+',
  },
  {
    id: '8',
    type: 'truth',
    text: 'Bạn đã bao giờ có ảo tưởng về ai đó trong phòng này chưa?',
    category: '18+',
  },
  {
    id: '9',
    type: 'truth',
    text: 'Bạn đã bao giờ hôn nhiều hơn một người trong cùng một ngày?',
    category: '18+',
  },
  {
    id: '10',
    type: 'truth',
    text: 'Bạn đã bao giờ có cảm xúc với người cùng giới không?',
    category: '18+',
  },
  {
    id: '11',
    type: 'dare',
    text: 'Hãy mô tả chi tiết lần "đầu tiên" của bạn.',
    category: '18+',
  },
  {
    id: '12',
    type: 'truth',
    text: 'Bạn đã bao giờ bị phát hiện khi đang "tự sướng"?',
    category: '18+',
  },
  {
    id: '13',
    type: 'truth',
    text: 'Bạn thích tư thế nào nhất?',
    category: '18+',
  },
  {
    id: '14',
    type: 'truth',
    text: 'Bạn đã bao giờ nghĩ về việc "qua đêm" với ai đó trong phòng này?',
    category: '18+',
  },
  {
    id: '15',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" ở nơi công cộng chưa?',
    category: '18+',
  },
  {
    id: '16',
    type: 'truth',
    text: 'Bạn đã bao giờ lừa dối người yêu chưa?',
    category: '18+',
  },
  {
    id: '17',
    type: 'truth',
    text: 'Bạn đã bao giờ xem phim người lớn với bạn bè chưa?',
    category: '18+',
  },
  {
    id: '18',
    type: 'truth',
    text: 'Bạn đã bao giờ có cảm xúc với người lớn tuổi hơn nhiều chưa?',
    category: '18+',
  },
  {
    id: '19',
    type: 'truth',
    text: 'Điều gì khiến bạn cảm thấy xấu hổ nhất khi "lên giường"?',
    category: '18+',
  },
  {
    id: '20',
    type: 'truth',
    text: 'Bạn đã bao giờ dùng đồ chơi người lớn chưa?',
    category: '18+',
  },
  {
    id: '21',
    type: 'dare',
    text: 'Hãy mô tả người trong phòng mà bạn thấy hấp dẫn nhất.',
    category: '18+',
  },
  {
    id: '22',
    type: 'truth',
    text: 'Bạn đã bao giờ có ảo tưởng về người nổi tiếng nào?',
    category: '18+',
  },
  {
    id: '23',
    type: 'truth',
    text: 'Bạn đã bao giờ "tự sướng" khi nghĩ về ai đó trong phòng này?',
    category: '18+',
  },
  {
    id: '24',
    type: 'truth',
    text: 'Bạn đã bao giờ có quan hệ "một đêm" chưa?',
    category: '18+',
  },
  {
    id: '25',
    type: 'truth',
    text: 'Bạn đã bao giờ bị từ chối khi muốn "gần gũi" với ai đó?',
    category: '18+',
  },
  {
    id: '26',
    type: 'truth',
    text: 'Bạn thích được nói những lời thế nào khi "lên giường"?',
    category: '18+',
  },
  {
    id: '27',
    type: 'truth',
    text: 'Bạn đã bao giờ có ảo tưởng về tình huống "ba người" chưa?',
    category: '18+',
  },
  {
    id: '28',
    type: 'truth',
    text: 'Bạn đã bao giờ hối hận sau khi "lên giường" với ai đó?',
    category: '18+',
  },
  {
    id: '29',
    type: 'truth',
    text: 'Bạn đã bao giờ giả vờ "lên đỉnh" chưa?',
    category: '18+',
  },
  {
    id: '30',
    type: 'truth',
    text: 'Bạn đã bao giờ bị bắt gặp khi đang xem nội dung người lớn?',
    category: '18+',
  },
  {
    id: '31',
    type: 'dare',
    text: 'Hãy kể về ảo tưởng "bí mật" nhất của bạn.',
    category: '18+',
  },
  {
    id: '32',
    type: 'truth',
    text: 'Bạn đã bao giờ có cảm xúc với người đã có gia đình chưa?',
    category: '18+',
  },
  {
    id: '33',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" khi có người khác ở gần?',
    category: '18+',
  },
  {
    id: '34',
    type: 'truth',
    text: 'Bạn đã bao giờ nói tên người khác khi đang "lên giường"?',
    category: '18+',
  },
  {
    id: '35',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" với người mà bạn không thích?',
    category: '18+',
  },
  {
    id: '36',
    type: 'truth',
    text: 'Bạn đã bao giờ có ảo tưởng về người mà bạn không nên có?',
    category: '18+',
  },
  {
    id: '37',
    type: 'truth',
    text: 'Bạn đã bao giờ bị người khác đánh giá về kỹ năng "giường chiếu"?',
    category: '18+',
  },
  {
    id: '38',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" ở nơi kỳ lạ nhất?',
    category: '18+',
  },
  {
    id: '39',
    type: 'truth',
    text: 'Bạn đã bao giờ có ảo tưởng về vai diễn nào đó?',
    category: '18+',
  },
  {
    id: '40',
    type: 'truth',
    text: 'Bạn đã bao giờ "tự sướng" khi xem phim bình thường?',
    category: '18+',
  },
  {
    id: '41',
    type: 'dare',
    text: 'Hãy mô tả chi tiết lần "lên đỉnh" tốt nhất của bạn.',
    category: '18+',
  },
  {
    id: '42',
    type: 'truth',
    text: 'Bạn đã bao giờ bị từ chối vì "kích thước" không phù hợp?',
    category: '18+',
  },
  {
    id: '43',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" với người lạ chưa?',
    category: '18+',
  },
  {
    id: '44',
    type: 'truth',
    text: 'Bạn đã bao giờ bị phát hiện khi đang "làm chuyện ấy"?',
    category: '18+',
  },
  {
    id: '45',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" khi đang say rượu?',
    category: '18+',
  },
  {
    id: '46',
    type: 'truth',
    text: 'Bạn đã bao giờ có ảo tưởng về việc bị người khác nhìn thấy khi "làm chuyện ấy"?',
    category: '18+',
  },
  {
    id: '47',
    type: 'truth',
    text: 'Điều gì là ranh giới mà bạn không bao giờ vượt qua trong chuyện "giường chiếu"?',
    category: '18+',
  },
  {
    id: '48',
    type: 'truth',
    text: 'Bạn đã bao giờ nói dối về số người mà bạn đã "lên giường" cùng?',
    category: '18+',
  },
  {
    id: '49',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" với người mà bạn biết là không nên?',
    category: '18+',
  },

  // New 18+ Truth questions
  {
    id: '50',
    type: 'truth',
    text: 'Lần đầu tiên bạn "hôn" là bao nhiêu tuổi?',
    category: '18+',
  },
  {
    id: '51',
    type: 'truth',
    text: 'Bạn đã từng yêu thầm ai mà không dám nói chưa?',
    category: '18+',
  },
  {
    id: '52',
    type: 'truth',
    text: 'Bạn đã từng ngủ nude chưa?',
    category: '18+',
  },
  {
    id: '53',
    type: 'truth',
    text: 'Điểm nhạy cảm nhất trên cơ thể bạn là gì?',
    category: '18+',
  },
  {
    id: '54',
    type: 'truth',
    text: 'Bạn thích kiểu người như thế nào khi yêu?',
    category: '18+',
  },
  {
    id: '55',
    type: 'truth',
    text: 'Bạn đã từng có "one night stand" chưa?',
    category: '18+',
  },
  {
    id: '56',
    type: 'truth',
    text: 'Lần quan hệ đầu tiên của bạn diễn ra ở đâu?',
    category: '18+',
  },
  {
    id: '58',
    type: 'truth',
    text: 'Điều điên rồ nhất bạn từng làm trong chuyện ấy là gì?',
    category: '18+',
  },
  {
    id: '59',
    type: 'truth',
    text: 'Từng tưởng tượng làm chuyện ấy với người nổi tiếng nào?',
    category: '18+',
  },
  {
    id: '60',
    type: 'truth',
    text: 'Bạn đã từng xem phim người lớn khi nào?',
    category: '18+',
  },
  {
    id: '61',
    type: 'truth',
    text: 'Bạn có thường xuyên thủ dâm không?',
    category: '18+',
  },
  {
    id: '62',
    type: 'truth',
    text: 'Bạn đã từng gửi ảnh sexy cho ai chưa?',
    category: '18+',
  },
  {
    id: '63',
    type: 'truth',
    text: 'Có bao giờ bị bắt quả tang khi đang "làm chuyện ấy" chưa?',
    category: '18+',
  },
  {
    id: '64',
    type: 'truth',
    text: 'Bạn có thích làm chuyện ấy vào buổi sáng không?',
    category: '18+',
  },
  {
    id: '65',
    type: 'truth',
    text: 'Tư thế yêu yêu thích của bạn là gì?',
    category: '18+',
  },
  {
    id: '66',
    type: 'truth',
    text: 'Bạn đã từng thử sexting chưa?',
    category: '18+',
  },
  {
    id: '67',
    type: 'truth',
    text: 'Bạn từng có mối quan hệ mập mờ với ai chưa?',
    category: '18+',
  },
  {
    id: '68',
    type: 'truth',
    text: 'Bạn đã từng quan hệ ở nơi công cộng chưa?',
    category: '18+',
  },
  {
    id: '69',
    type: 'truth',
    text: 'Có bao giờ yêu hai người cùng lúc chưa?',
    category: '18+',
  },
  {
    id: '70',
    type: 'truth',
    text: 'Bạn đã từng "crush" sếp hoặc đồng nghiệp chưa?',
    category: '18+',
  },
  {
    id: '71',
    type: 'truth',
    text: 'Từng nhắn tin tán tỉnh ai đó dù biết người ta đã có người yêu?',
    category: '18+',
  },
  {
    id: '72',
    type: 'truth',
    text: 'Bạn có thường xuyên giả vờ "lên đỉnh" không?',
    category: '18+',
  },
  {
    id: '73',
    type: 'truth',
    text: 'Nếu phải chọn một người trong nhóm này để ngủ cùng, bạn sẽ chọn ai?',
    category: '18+',
  },
  {
    id: '74',
    type: 'truth',
    text: 'Bạn đã từng bị "từ chối" khi muốn thân mật chưa?',
    category: '18+',
  },

  // New 18+ Dare questions
  {
    id: '75',
    type: 'dare',
    text: 'Hôn một người bất kỳ trong nhóm 5 giây.',
    category: '18+',
  },
  {
    id: '76',
    type: 'dare',
    text: 'Gọi điện tỏ tình với người mà bạn từng thích.',
    category: '18+',
  },
  {
    id: '77',
    type: 'dare',
    text: 'Giả vờ "rên" 10 giây thật tự nhiên.',
    category: '18+',
  },
  {
    id: '78',
    type: 'dare',
    text: 'Gửi icon 💦 hoặc 🍆 cho người bất kỳ trong danh bạ.',
    category: '18+',
  },
  {
    id: '79',
    type: 'dare',
    text: 'Hôn một bộ phận bất kỳ trên cơ thể người bên cạnh.',
    category: '18+',
  },
  {
    id: '80',
    type: 'dare',
    text: 'Giả làm "người quyến rũ" trong 15 giây.',
    category: '18+',
  },
  {
    id: '81',
    type: 'dare',
    text: 'Chụp ảnh selfie sexy và đăng story (ẩn với ai đó tùy chọn).',
    category: '18+',
  },
  {
    id: '82',
    type: 'dare',
    text: 'Nhảy sexy dance trong 30 giây.',
    category: '18+',
  },
  {
    id: '83',
    type: 'dare',
    text: 'Đọc to một tin nhắn "mùi mẫn" gần đây bạn gửi hoặc nhận.',
    category: '18+',
  },
  {
    id: '84',
    type: 'dare',
    text: 'Gọi video cho crush và nói: "Anh/em nhớ anh/em lắm!"',
    category: '18+',
  },
  {
    id: '85',
    type: 'dare',
    text: 'Cởi một món đồ trên người (trừ đồ lót).',
    category: '18+',
  },
  {
    id: '86',
    type: 'dare',
    text: 'Nằm vào lòng người đối diện 1 phút.',
    category: '18+',
  },
  {
    id: '87',
    type: 'dare',
    text: 'Tạo tư thế yêu gợi cảm với gối trong 10 giây.',
    category: '18+',
  },
  {
    id: '88',
    type: 'dare',
    text: 'Diễn lại cảnh "tỏ tình nóng bỏng" trong phim Hàn.',
    category: '18+',
  },
  {
    id: '89',
    type: 'dare',
    text: 'Nhắn tin "Anh/em muốn quá!" cho người bạn bất kỳ chọn.',
    category: '18+',
  },
  {
    id: '90',
    type: 'dare',
    text: 'Mô tả một giấc mơ ướt át bạn từng mơ.',
    category: '18+',
  },
  {
    id: '91',
    type: 'dare',
    text: 'Thử nói chuyện gợi tình trong 30 giây.',
    category: '18+',
  },
  {
    id: '92',
    type: 'dare',
    text: 'Nhảy múa gợi cảm trên ghế như đang ở quán bar.',
    category: '18+',
  },
  {
    id: '93',
    type: 'dare',
    text: 'Để người khác vẽ hoặc viết lên bụng bạn một từ sexy.',
    category: '18+',
  },
  {
    id: '94',
    type: 'dare',
    text: 'Tạo tiếng "rên" giả như đang "vui vẻ" trong 5 giây.',
    category: '18+',
  },
  {
    id: '95',
    type: 'dare',
    text: 'Hôn tay người bạn gần nhất.',
    category: '18+',
  },
  {
    id: '96',
    type: 'dare',
    text: 'Để người khác kiểm tra mục ảnh gần đây nhất của bạn.',
    category: '18+',
  },
  {
    id: '97',
    type: 'dare',
    text: 'Đọc tin nhắn gần nhất trong nhóm kín hoặc riêng tư.',
    category: '18+',
  },
  {
    id: '98',
    type: 'dare',
    text: 'Gọi video cho một người bất kỳ và nói: "Anh/em đang nhớ cái ôm của anh/em!"',
    category: '18+',
  },
  {
    id: '99',
    type: 'dare',
    text: 'Mô phỏng lại một tư thế "nóng bỏng" nhưng chỉ dùng đồ vật (gối, khăn,...).',
    category: '18+',
  },

  // 100 new 18+ questions
  {
    id: '100',
    type: 'truth',
    text: 'Bạn đã bao giờ "lỡ" gọi tên người cũ khi đang ở với người mới chưa?',
    category: '18+',
  },
  {
    id: '101',
    type: 'truth',
    text: 'Nơi công cộng kỳ lạ nhất mà bạn từng muốn "làm chuyện ấy" là đâu?',
    category: '18+',
  },
  {
    id: '102',
    type: 'dare',
    text: 'Nhắn tin cho người yêu cũ và nói rằng bạn nhớ họ.',
    category: '18+',
  },
  {
    id: '103',
    type: 'truth',
    text: 'Bạn đã bao giờ bị hấp dẫn bởi bạn thân của người yêu mình chưa?',
    category: '18+',
  },
  {
    id: '104',
    type: 'dare',
    text: 'Đọc to tin nhắn "nhạy cảm" gần đây nhất trong điện thoại của bạn.',
    category: '18+',
  },
  {
    id: '106',
    type: 'dare',
    text: 'Mô tả chi tiết lần "lên đỉnh" gần đây nhất của bạn.',
    category: '18+',
  },
  {
    id: '107',
    type: 'truth',
    text: 'Bạn đã từng cảm thấy có thu hút đặc biệt với ai đó "cấm đoán" chưa?',
    category: '18+',
  },
  {
    id: '108',
    type: 'dare',
    text: 'Gọi điện cho người yêu (hoặc crush) và nói những lời gợi cảm.',
    category: '18+',
  },
  {
    id: '109',
    type: 'truth',
    text: 'Bạn thích được "nói chuyện bẩn" khi "làm chuyện ấy" không?',
    category: '18+',
  },
  {
    id: '110',
    type: 'dare',
    text: 'Uống một shot rượu từ cơ thể của người khác.',
    category: '18+',
  },
  {
    id: '111',
    type: 'truth',
    text: 'Bạn đã bao giờ sử dụng ứng dụng hẹn hò chỉ để "qua đêm" chưa?',
    category: '18+',
  },
  {
    id: '112',
    type: 'dare',
    text: 'Ngồi trên đùi người chơi khác trong 2 phút.',
    category: '18+',
  },
  {
    id: '113',
    type: 'truth',
    text: 'Bạn đã bao giờ bị thu hút bởi người đã có gia đình chưa?',
    category: '18+',
  },
  {
    id: '114',
    type: 'dare',
    text: 'Tạo âm thanh "gợi cảm" trong 10 giây.',
    category: '18+',
  },
  {
    id: '115',
    type: 'truth',
    text: 'Có lúc nào bạn cảm thấy không hài lòng về "kích thước" của mình không?',
    category: '18+',
  },
  {
    id: '116',
    type: 'dare',
    text: 'Massage vai cho người bên cạnh trong 30 giây.',
    category: '18+',
  },
  {
    id: '117',
    type: 'truth',
    text: 'Bạn đã bao giờ "nhìn trộm" ai đó đang thay đồ hoặc tắm chưa?',
    category: '18+',
  },
  {
    id: '118',
    type: 'dare',
    text: 'Mô tả chi tiết ảo tưởng "bí mật" nhất của bạn.',
    category: '18+',
  },
  {
    id: '119',
    type: 'truth',
    text: 'Bạn đã bao giờ bị "cắm sừng" hoặc "cắm sừng" ai đó chưa?',
    category: '18+',
  },
  {
    id: '120',
    type: 'dare',
    text: 'Diễn tả khuôn mặt "lên đỉnh" của bạn trong 5 giây.',
    category: '18+',
  },
  {
    id: '121',
    type: 'truth',
    text: 'Bạn đã bao giờ sử dụng đồ chơi người lớn khi "tự sướng" chưa?',
    category: '18+',
  },
  {
    id: '122',
    type: 'dare',
    text: 'Nhảy sexy dance cho người chơi khác xem trong 30 giây.',
    category: '18+',
  },
  {
    id: '123',
    type: 'truth',
    text: 'Bạn đã bao giờ bị bắt gặp đang xem nội dung người lớn chưa?',
    category: '18+',
  },
  {
    id: '124',
    type: 'dare',
    text: 'Để một người chơi khác vẽ lên người bạn bằng son môi.',
    category: '18+',
  },
  {
    id: '125',
    type: 'truth',
    text: 'Bạn đã bao giờ cảm thấy hối hận sau khi "lên giường" với ai đó chưa?',
    category: '18+',
  },
  {
    id: '126',
    type: 'dare',
    text: 'Thể hiện tư thế yêu thích của bạn bằng cách sử dụng đồ vật.',
    category: '18+',
  },
  {
    id: '127',
    type: 'truth',
    text: 'Bạn đã bao giờ bị đánh giá thấp về "khả năng" trên giường chưa?',
    category: '18+',
  },
  {
    id: '128',
    type: 'dare',
    text: 'Nhún nhảy gợi cảm trong 20 giây theo nhạc.',
    category: '18+',
  },
  {
    id: '129',
    type: 'truth',
    text: 'Bạn đã bao giờ làm điều gì "quá đà" khi say rượu chưa?',
    category: '18+',
  },
  {
    id: '130',
    type: 'dare',
    text: 'Hiện tin nhắn gần đây nhất với "người thứ ba" (nếu có).',
    category: '18+',
  },
  {
    id: '131',
    type: 'truth',
    text: 'Bạn có thường xuyên "tự sướng" trong tuần không?',
    category: '18+',
  },
  {
    id: '132',
    type: 'dare',
    text: 'Uống một shot đồ uống từ rốn của một người khác.',
    category: '18+',
  },
  {
    id: '133',
    type: 'truth',
    text: 'Thời gian "lâu" nhất bạn từng "làm chuyện ấy" là bao lâu?',
    category: '18+',
  },
  {
    id: '134',
    type: 'dare',
    text: 'Để người khác cho bạn ăn đồ ngọt bằng miệng.',
    category: '18+',
  },
  {
    id: '135',
    type: 'truth',
    text: 'Bạn đã bao giờ "nhìn trộm" người khác đang "làm chuyện ấy" chưa?',
    category: '18+',
  },
  {
    id: '136',
    type: 'dare',
    text: 'Thực hiện một điệu nhảy gợi cảm cho nhóm xem.',
    category: '18+',
  },
  {
    id: '137',
    type: 'truth',
    text: 'Bạn đã bao giờ bị phát hiện đang "tự sướng" chưa?',
    category: '18+',
  },
  {
    id: '138',
    type: 'dare',
    text: 'Nhắn tin cho người bạn chọn với nội dung: "Tối nay anh/em rảnh không?"',
    category: '18+',
  },
  {
    id: '139',
    type: 'truth',
    text: 'Bạn đã bao giờ có những suy nghĩ "đen tối" về bạn thân của mình chưa?',
    category: '18+',
  },
  {
    id: '140',
    type: 'dare',
    text: 'Hôn vào cổ người chơi bên cạnh.',
    category: '18+',
  },
  {
    id: '141',
    type: 'truth',
    text: 'Bạn đã bao giờ hối hận vì đã "từ chối" ai đó chưa?',
    category: '18+',
  },
  {
    id: '142',
    type: 'dare',
    text: 'Gửi một tin nhắn gợi cảm cho người bạn chọn ngẫu nhiên trong danh bạ.',
    category: '18+',
  },
  {
    id: '143',
    type: 'truth',
    text: 'Đâu là nơi kỳ lạ nhất bạn từng "tự sướng"?',
    category: '18+',
  },
  {
    id: '144',
    type: 'dare',
    text: 'Kể chi tiết về lần đầu tiên bạn "làm chuyện ấy".',
    category: '18+',
  },
  {
    id: '145',
    type: 'truth',
    text: 'Bạn thích người khác "cư xử" thế nào khi "lên giường"?',
    category: '18+',
  },
  {
    id: '146',
    type: 'dare',
    text: 'Để người chơi khác đút cho bạn ăn một thứ gì đó.',
    category: '18+',
  },
  {
    id: '147',
    type: 'truth',
    text: 'Bạn đã bao giờ "động chạm" không phù hợp với ai đó chưa?',
    category: '18+',
  },
  {
    id: '148',
    type: 'dare',
    text: 'Đọc to một đoạn trong sách/truyện "người lớn".',
    category: '18+',
  },
  {
    id: '149',
    type: 'truth',
    text: 'Bạn thích người yêu mình "nói bẩn" khi "làm chuyện ấy" không?',
    category: '18+',
  },
  {
    id: '150',
    type: 'dare',
    text: 'Mô tả chi tiết trải nghiệm "kỳ lạ" nhất của bạn khi "làm chuyện ấy".',
    category: '18+',
  },
  {
    id: '151',
    type: 'truth',
    text: 'Bạn đã bao giờ bị phát hiện đang xem nội dung "người lớn" chưa?',
    category: '18+',
  },
  {
    id: '152',
    type: 'dare',
    text: 'Thực hiện một hành động quyến rũ với người ngồi bên cạnh.',
    category: '18+',
  },
  {
    id: '153',
    type: 'truth',
    text: 'Bạn thích phim "người lớn" thể loại nào nhất?',
    category: '18+',
  },
  {
    id: '154',
    type: 'dare',
    text: 'Nhắn tin cho người yêu (hoặc crush) nói rằng bạn đang nhớ họ rất nhiều.',
    category: '18+',
  },
  {
    id: '155',
    type: 'truth',
    text: 'Trang phục gợi cảm nhất mà bạn thích là gì?',
    category: '18+',
  },
  {
    id: '156',
    type: 'dare',
    text: 'Nhảy vũ điệu "sexy" tự chọn trong 20 giây.',
    category: '18+',
  },
  {
    id: '157',
    type: 'truth',
    text: 'Bạn đã bao giờ "lên giường" với người lớn tuổi hơn nhiều chưa?',
    category: '18+',
  },
  {
    id: '158',
    type: 'dare',
    text: 'Tạo khuôn mặt "hưng phấn" trong 5 giây.',
    category: '18+',
  },
  {
    id: '159',
    type: 'truth',
    text: 'Bạn đã bao giờ bị ai đó "block" vì quá "thả thính" chưa?',
    category: '18+',
  },
  {
    id: '160',
    type: 'dare',
    text: 'Gọi video cho một người bạn và nói "Anh/em đang nhớ anh/em quá!"',
    category: '18+',
  },
  {
    id: '161',
    type: 'truth',
    text: 'Bạn đã bao giờ thức cả đêm để "làm chuyện ấy" chưa?',
    category: '18+',
  },
  {
    id: '162',
    type: 'dare',
    text: 'Để một người chơi khác vẽ lên má bạn bằng son môi.',
    category: '18+',
  },
  {
    id: '163',
    type: 'truth',
    text: 'Bạn có từng mong muốn "thử" với người cùng giới không?',
    category: '18+',
  },
  {
    id: '164',
    type: 'dare',
    text: 'Thể hiện cách bạn thường "quyến rũ" người khác.',
    category: '18+',
  },
  {
    id: '165',
    type: 'truth',
    text: 'Bạn đã bao giờ nói dối về "số lượng" người bạn đã từng hẹn hò chưa?',
    category: '18+',
  },
  {
    id: '166',
    type: 'dare',
    text: 'Hôn tay của người ngồi đối diện trong 5 giây.',
    category: '18+',
  },
  {
    id: '167',
    type: 'truth',
    text: 'Bạn đã bao giờ "giả vờ" cao trào chưa?',
    category: '18+',
  },
  {
    id: '168',
    type: 'dare',
    text: 'Ngồi trên đùi người chơi đối diện trong 1 phút.',
    category: '18+',
  },
  {
    id: '169',
    type: 'truth',
    text: 'Bạn đã bao giờ có ảo tưởng về "người quyền lực" nào đó chưa?',
    category: '18+',
  },
  {
    id: '170',
    type: 'dare',
    text: 'Kể tên 5 tư thế "yêu" mà bạn biết.',
    category: '18+',
  },
  {
    id: '171',
    type: 'truth',
    text: 'Bạn đã bao giờ bị ám ảnh về "chuyện ấy" với ai đó chưa?',
    category: '18+',
  },
  {
    id: '172',
    type: 'dare',
    text: 'Nhắn tin cho người bạn chọn với nội dung: "Tối nay anh/em rảnh không?"',
    category: '18+',
  },
  {
    id: '173',
    type: 'truth',
    text: 'Bạn nghĩ mình "mạnh mẽ" đến mức nào trên giường?',
    category: '18+',
  },
  {
    id: '174',
    type: 'dare',
    text: 'Để ai đó trong nhóm cho bạn ăn một thứ gì đó bằng miệng.',
    category: '18+',
  },
  {
    id: '175',
    type: 'truth',
    text: 'Bạn đã bao giờ bị từ chối "lên giường" vì lý do nào đó chưa?',
    category: '18+',
  },
  {
    id: '176',
    type: 'dare',
    text: 'Hôn má người chơi khác trong 3 giây.',
    category: '18+',
  },
  {
    id: '177',
    type: 'truth',
    text: 'Điều gì khiến bạn thấy khó chịu nhất khi "làm chuyện ấy"?',
    category: '18+',
  },
  {
    id: '178',
    type: 'dare',
    text: 'Tạo một âm thanh "gợi cảm" mà bạn thường tạo khi "lên đỉnh".',
    category: '18+',
  },
  {
    id: '179',
    type: 'truth',
    text: 'Bạn đã bao giờ cảm thấy sợ hãi khi "làm chuyện ấy" chưa?',
    category: '18+',
  },
  {
    id: '180',
    type: 'dare',
    text: 'Làm động tác "push-up" lên người nằm dưới sàn trong 15 giây.',
    category: '18+',
  },
  {
    id: '181',
    type: 'truth',
    text: 'Bạn có thích xem người khác "làm chuyện ấy" không?',
    category: '18+',
  },
  {
    id: '182',
    type: 'dare',
    text: 'Tiết lộ một bí mật "đen tối" về chuyện tình cảm của bạn.',
    category: '18+',
  },
  {
    id: '183',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" ở nơi công cộng chưa? Nếu có, ở đâu?',
    category: '18+',
  },
  {
    id: '184',
    type: 'dare',
    text: 'Nhảy sexy dance trên nhạc trong 30 giây.',
    category: '18+',
  },
  {
    id: '185',
    type: 'truth',
    text: 'Bạn đã bao giờ nghĩ về việc "làm chuyện ấy" với người lạ chưa?',
    category: '18+',
  },
  {
    id: '186',
    type: 'dare',
    text: 'Đọc to lời một bài hát gợi cảm bạn biết.',
    category: '18+',
  },
  {
    id: '187',
    type: 'truth',
    text: 'Bạn đã bao giờ sử dụng "đồ chơi" khi "làm chuyện ấy" chưa?',
    category: '18+',
  },
  {
    id: '188',
    type: 'dare',
    text: 'Mô tả chi tiết "người trong mộng" của bạn là như thế nào.',
    category: '18+',
  },
  {
    id: '189',
    type: 'truth',
    text: 'Bạn đã bao giờ có những giấc mơ "ướt át" về ai đó mà bạn biết chưa?',
    category: '18+',
  },
  {
    id: '190',
    type: 'dare',
    text: 'Nhảy múa gợi cảm theo nhạc trong 20 giây.',
    category: '18+',
  },
  {
    id: '191',
    type: 'truth',
    text: 'Bạn đã bao giờ nghĩ về việc "làm chuyện ấy" với nhiều người cùng lúc chưa?',
    category: '18+',
  },
  {
    id: '192',
    type: 'dare',
    text: 'Gửi một emoji "gợi ý" cho người trong danh bạ mà bạn nghĩ họ sẽ hiểu ý.',
    category: '18+',
  },
  {
    id: '193',
    type: 'truth',
    text: 'Bạn đã bao giờ bị "cấm vận" sau khi "làm chuyện ấy" chưa?',
    category: '18+',
  },
  {
    id: '194',
    type: 'dare',
    text: 'Kể tên 3 bộ phận "nhạy cảm" trên cơ thể mà bạn thích được chạm vào nhất.',
    category: '18+',
  },
  {
    id: '195',
    type: 'truth',
    text: 'Bạn đã bao giờ bị ai đó làm bạn thất vọng trên giường chưa?',
    category: '18+',
  },
  {
    id: '196',
    type: 'dare',
    text: 'Bắt chước âm thanh "khoái cảm" của bạn trong 5 giây.',
    category: '18+',
  },
  {
    id: '197',
    type: 'truth',
    text: 'Bạn đã bao giờ "làm chuyện ấy" khi có người khác ở trong cùng một phòng chưa?',
    category: '18+',
  },
  {
    id: '198',
    type: 'dare',
    text: 'Nhắn tin cho crush: "Anh/em đang làm gì vậy? Em/anh đang nhớ anh/em."',
    category: '18+',
  },
  {
    id: '199',
    type: 'truth',
    text: 'Bạn đã bao giờ cảm thấy hối hận sau khi "tự sướng" chưa?',
    category: '18+',
  },
  {
    id: '47a4b4ce-8ac4-4f2e-b61b-05942fe1c350',
    type: 'dare',
    text: 'Đọc to một dòng tin nhắn sex (có thể bịa) như thể bạn đang sexting thật.',
    category: '18+',
  },
  {
    id: 'b675d9dc-68e6-4427-898e-b7c5b7768c1e',
    type: 'dare',
    text: 'Hôn lên tay hoặc cổ ai đó trong nhóm như một cảnh trong phim người lớn.',
    category: '18+',
  },
  {
    id: 'a057f8e0-50f5-4ec5-a20e-2f8b21248d46',
    type: 'dare',
    text: 'Giả vờ đang được làm tình trong 10 giây – âm thanh, biểu cảm đầy đủ.',
    category: '18+',
  },
  {
    id: '654cd196-c9be-4e86-a75c-63573ea57fd7',
    type: 'dare',
    text: 'Gỡ một mảnh quần áo bạn đang mặc (nếu an toàn, có thể giả bộ cũng được 😜)',
    category: '18+',
  },
  {
    id: 'c8ed0678-b2a9-41e0-9427-f2ae1b33a2f7',
    type: 'dare',
    text: 'Mô tả chi tiết cách bạn quyến rũ người khác trên giường, từ ánh mắt đến động tác tay.',
    category: '18+',
  },
  {
    id: 'sdvasd-b2a9-41e0-9427-f2ae1b33a2f7',
    type: 'truth',
    text: `💋 Bạn đã từng thủ dâm trong nhà tắm, nơi công cộng, hoặc một nơi "không nên làm" chưa? Ở đâu?`,
    category: '18+',
  },
  {
    id: 'e5a7c3b1-9d2f-4c8a-b6e3-f1d8e9a2c0b4',
    type: 'truth',
    text: '🔥 Lần gần nhất bạn "tự xử" là khi nào? Có nghĩ đến ai trong nhóm khi làm không?',
    category: '18+',
  },
  {
    id: 'f8d6e4c2-a1b3-4c5d-9e7f-8a9b0c1d2e3f',
    type: 'truth',
    text: '😈 Bạn từng giả vờ lên đỉnh chưa? Với ai? Vì sao lại giả vờ?',
    category: '18+',
  },
  {
    id: 'a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6',
    type: 'truth',
    text: '💦 Bạn đã từng "xem phim người lớn" mấy lần trong 1 ngày? Có bao giờ vừa xem vừa nghĩ đến người thật ngoài đời không?',
    category: '18+',
  },
  {
    id: 'c5d6e7f8-a9b0-c1d2-e3f4-a5b6c7d8e9f0',
    type: 'truth',
    text: '🤭 Ai trong nhóm chơi này bạn muốn thử một lần lên giường nhất? Lý do?',
    category: '18+',
  },
  {
    id: 'b7c8d9e0-f1a2-b3c4-d5e6-f7a8b9c0d1e2',
    type: 'truth',
    text: '🥵 Lần "mạnh bạo" hoặc táo bạo nhất bạn từng trải qua là như thế nào? Kể thật chi tiết.',
    category: '18+',
  },
  {
    id: 'd2e3f4a5-b6c7-d8e9-f0a1-b2c3d4e5f6a7',
    type: 'truth',
    text: '😇 Bạn đã từng nhắn tin sex (sexting) với ai? Câu nào bạn thấy bản thân dâm nhất khi gửi?',
    category: '18+',
  },
  {
    id: 'e5f6a7b8-c9d0-e1f2-a3b4-c5d6e7f8a9b0',
    type: 'truth',
    text: '🛏️ Tư thế bạn yêu thích nhất là gì? Đã từng thử ngoài giường chưa? Ở đâu?',
    category: '18+',
  },
  {
    id: 'f8a9b0c1-d2e3-f4a5-b6c7-d8e9f0a1b2c3',
    type: 'truth',
    text: '🔒 Bạn có bí mật tình dục nào chưa từng dám kể với ai không? Sẵn sàng chia sẻ chứ?',
    category: '18+',
  },
  {
    id: 'a3b4c5d6-e7f8-a9b0-c1d2-e3f4a5b6c7d8',
    type: 'truth',
    text: '👀 Từng lén nhìn ai đó thay đồ hoặc trong tình huống nhạy cảm chưa? Phản ứng của bạn lúc đó thế nào?',
    category: '18+',
  },

  {
    id: 'a9b8c7d6-e5f4-g3h2-i1j0-k9l8m7n6o5p4',
    type: 'dare',
    text: '😈 Nếu tối nay bạn là "nô lệ tình dục" của người bên trái bạn, bạn nghĩ họ sẽ bắt bạn làm gì đầu tiên? Mô tả chi tiết.',
    category: '18+',
  },
  {
    id: 'b8c7d6e5-f4g3-h2i1-j0k9-l8m7n6o5p4q3',
    type: 'dare',
    text: '👠 Giả sử bạn là gái ngành/phi công, mô tả buổi gặp khách đầu tiên mà bạn "quá trời thăng hoa" – khách đó là ai trong nhóm?',
    category: '18+',
  },
  {
    id: 'c7d6e5f4-g3h2-i1j0-k9l8-m7n6o5p4q3r2',
    type: 'dare',
    text: '🔥 Nếu bạn bị trói vào giường và không thể phản kháng, ai trong nhóm bạn muốn thấy đứng ở cuối giường? Họ sẽ làm gì bạn đầu tiên?',
    category: '18+',
  },
  {
    id: 'd6e5f4g3-h2i1-j0k9-l8m7-n6o5p4q3r2s1',
    type: 'dare',
    text: '🍷 Bạn đang say và "gạ" người bạn thân của mình – bạn sẽ nói gì để quyến rũ họ? Nhập vai và nói luôn.',
    category: '18+',
  },
  {
    id: 'e5f4g3h2-i1j0-k9l8-m7n6-o5p4q3r2s1t0',
    type: 'dare',
    text: '💋 Bạn là thầy/cô giáo sexy, và một học trò của bạn đang phá luật – bạn trừng phạt học trò thế nào? Tên người đó trong nhóm là gì?',
    category: '18+',
  },
  {
    id: 'f4g3h2i1-j0k9-l8m7-n6o5-p4q3r2s1t0u9',
    type: 'dare',
    text: '🛏️ Nếu bạn bị nhốt qua đêm trong phòng khách sạn với người đối diện, bạn nghĩ ai sẽ cởi đồ trước? Kể chi tiết chuyện có thể xảy ra.',
    category: '18+',
  },
  {
    id: 'g3h2i1j0-k9l8-m7n6-o5p4-q3r2s1t0u9v8',
    type: 'dare',
    text: '💦 Bạn là người yêu cũ quay lại để "đòi lại một đêm", bạn sẽ chọn ai trong nhóm? Và đêm đó sẽ bắt đầu như thế nào?',
    category: '18+',
  },
  {
    id: 'h2i1j0k9-l8m7-n6o5-p4q3-r2s1t0u9v8w7',
    type: 'dare',
    text: '🕯️ Mô tả một buổi "hẹn hò ướt át" mà bạn đang tưởng tượng – ánh nến, rượu vang và một cái giường king size. Nhân vật chính đi cùng là ai trong nhóm?',
    category: '18+',
  },
  {
    id: 'i1j0k9l8-m7n6-o5p4-q3r2-s1t0u9v8w7x6',
    type: 'dare',
    text: '🤤 Nếu bạn là diễn viên phim người lớn, bạn sẽ chọn ai trong nhóm làm bạn diễn? Và cảnh quay đầu tiên của bạn là gì?',
    category: '18+',
  },
  {
    id: 'j0k9l8m7-n6o5-p4q3-r2s1-t0u9v8w7x6y5',
    type: 'dare',
    text: '📸 Bạn đang thực hiện 1 buổi chụp ảnh nude nghệ thuật – ai trong nhóm là nhiếp ảnh gia? Bạn sẽ tạo dáng ra sao để "khiêu khích" họ nhất?',
    category: '18+',
  },
];
